<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsCloud_Block_Customer_Payment_Cards_Add
 */
?>
<div class="page-title">
  <h1><?php echo $this->__('Add Payment Card') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<form id="card-setup-form" method="post" action="<?php echo $this->escapeUrl($this->getFormUrl()); ?>">

  <h2><?php echo $this->__('Billing Address'); ?></h2>

  <select name="address_id">
    <?php foreach ($this->getAddressList() as $id => $address): ?>
      <option value="<?php echo $this->escapeHtml($id); ?>"><?php echo $this->escapeHtml($address); ?></option>
    <?php endforeach; ?>
  </select>

  <div id="xpayments-iframe-container">
  </div>

  <div class="actions">
    <button id="widget-submit" class="button"><?php echo $this->__('Save Payment Card') ?></button>
  </div>

</form>

<div class="buttons-set">
  <p class="back-link">
    <a href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>">
      <small>&laquo;&nbsp;</small><?php echo $this->__('Back') ?>
    </a>
  </p>
</div>


<script type="text/javascript">
//<![CDATA[

var xpayments = new XPayments(<?php echo $this->getCardSetupWidgetSettings()->toJson(); ?>);

xpayments.load();

//]]>
</script>
